Convert dos line endings on the fly

diff --git a/mds b/mds
--- a/mds
+++ b/mds
@@ -117,41 +117,41 @@ if (( VERBOSE > 1 )); then
 fi
 
 +++ Check that the settings are valid +++
-# CHECK MAIN THEME
++++ CHECK MAIN THEME +++
 validTHEMES="/AnnArbor/Antibes/Bergen/Berkeley/Berlin/Boadilla/boxes/CambridgeUS/Copenhagen/Darmstadt/default/Dresden/Frankfurt/Goettingen/Hannover/Ilmenau/JuanLesPins/Luebeck/Madrid/Malmoe/Marburg/Montpellier/PaloAlto/Pittsburgh/Rochester/Singapore/Szeged/Warsaw/"
 if ! [[  $validTHEMES =~ /${THEME}/ ]]; then
     echo "ERROR: Invalid THEME '$THEME'. Valid choices are:${validTHEMES//\// }" 1>&2
     exit 1
 fi
-# CHECK COLORTHEME
++++ CHECK COLORTHEME +++
 validCOLORTHEMES="/albatross/beaver/beetle/crane/default/dolphin/dove/fly/lily/orchid/rose/seagull/seahorse/sidebartab/structure/whale/wolverine/"
 if ! [[  $validCOLORTHEMES =~ /${COLORTHEME}/ ]]; then
     echo "ERROR: Invalid COLORTHEME '$COLORTHEME'. Valid choices are:${validCOLORTHEMES//\// }" 1>&2
     exit 1
 fi
-# check INNERTHEME
++++ check INNERTHEME +++
 validINNERTHEMES="/default/circles/rectangles/rounded/inmargin/"
 if ! [[  $validINNERTHEMES =~ /${INNERTHEME}/ ]]; then
     echo "ERROR: Invalid INNERTHEME '$INNERTHEME'. Valid choices are:${validINNERTHEMES//\// }" 1>&2
     exit 1
 fi
-# check FONTTHEME
++++ check FONTTHEME +++
 validFONTTHEMES="/default/professionalfonts/structurebold/structureitalicserif/structuresmallcapsserif/serif/sansserif/"
 if ! [[  $validFONTTHEMES =~ /${FONTTHEME}/ ]]; then
     echo "ERROR: Invalid FONTTHEME '$FONTTHEME'. Valid choices are:${validFONTTHEMES//\// }" 1>&2
     exit 1
 fi
-# check HIGHLIGHT
++++ check HIGHLIGHT +++
 if [ "${HIGHLIGHT:-}" ]; then
-    validHIGHLIGHTS=$(pandoc --list-highlight-styles)
-    validHIGHLIGHTS=/${validHIGHLIGHTS//
-/\/}/
+    validHIGHLIGHTS=/$(pandoc --list-highlight-styles | tr '\r\n' '/')/
+#    validHIGHLIGHTS=/${validHIGHLIGHTS//
+#/\/}/
     if ! [[  $validHIGHLIGHTS =~ /${HIGHLIGHT}/ ]]; then
-        echo "ERROR: Invalid HIGHLIGHT stye '$HIGHLIGHT'. Valid choices are:${validHIGHLIGHTS//\// }" 1>&2
+        echo "ERROR: Invalid HIGHLIGHT style '$HIGHLIGHT'. Valid choices are:${validHIGHLIGHTS//\// }" 1>&2
         exit 1
     fi
 fi
-# check ASPECTRATIO
++++ check ASPECTRATIO +++
 if [ "${ASPECTRATIO:-}" ]; then
     validASPECTRATIOS="/1610/169/149/54/43/32/"
     if ! [[  $validASPECTRATIOS =~ /${ASPECTRATIO}/ ]]; then
@@ -159,7 +159,7 @@ if [ "${ASPECTRATIO:-}" ]; then
         exit 1
     fi
 fi
-# check LOGOONTITLE
++++ check LOGOONTITLE +++
 if [ "${LOGOONTITLE:-}" ]; then
     validLOGOONTITLES="/true/false/"
     if ! [[  $validLOGOONTITLES =~ /${LOGOONTITLE}/ ]]; then
@@ -167,28 +167,28 @@ if [ "${LOGOONTITLE:-}" ]; then
         exit 1
     fi
 fi
-# check LOGOHEIGHT
++++ check LOGOHEIGHT +++
 if [ "${LOGOHEIGHT:-}" ]; then
     if ! [[ $LOGOHEIGHT =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
         echo "ERROR: Invalid number '$LOGOHEIGHT' for LOGOHEIGHT." 1>&2
         exit 1
     fi
 fi
-# check LOGOWIDTH
++++ check LOGOWIDTH +++
 if [ "${LOGOWIDTH:-}" ]; then
     if ! [[ $LOGOWIDTH =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
         echo "ERROR: Invalid number '$LOGOWIDTH' for LOGOWIDTH." 1>&2
         exit 1
     fi
 fi
-# check LOGOUP
++++ check LOGOUP +++
 if [ "${LOGOUP:-}" ]; then
     if ! [[ $LOGOUP =~ ^\-?[0-9]*(\.[0-9]+)?$ ]]; then
         echo "ERROR: Invalid number '$LOGOUP' for LOGOUP." 1>&2
         exit 1
     fi
 fi
-# check LOGO
++++ check LOGO +++
 if [ "${LOGO:-}" ]; then
   compatibleTHEMES="/AnnArbor/Antibes/Bergen/Berkeley/Berlin/Boadilla/boxes/CambridgeUS/Copenhagen/Darmstadt/default/Dresden/Frankfurt/Ilmenau/JuanLesPins/Luebeck/Madrid/Malmoe/Montpellier/PaloAlto/Pittsburgh/Rochester/Singapore/Szeged/Warsaw/"
     if ! [[  $compatibleTHEMES =~ /${THEME}/ ]]; then
@@ -201,7 +201,7 @@ if [ "${LOGO:-}" ]; then
         exit 2
     fi
 fi
-# check FONTSIZE
++++ check FONTSIZE +++
 if [ "${FONTSIZE:-}" ]; then
     validFONTSIZES="/8pt/9pt/10pt/11pt/12pt/14pt/17pt/20pt/"
     if ! [[  $validFONTSIZES =~ /${FONTSIZE}/ ]]; then
@@ -209,7 +209,7 @@ if [ "${FONTSIZE:-}" ]; then
         exit 1
     fi
 fi
-# check FONTFAMILY
++++ check FONTFAMILY +++
 if [ "${FONTFAMILY:-}" ]; then
     validFONTFAMILIES=$(fc-list : family | tr ',' '\n' | sort -u)
     validFONTFAMILIES=/${validFONTFAMILIES//
@@ -219,7 +219,7 @@ if [ "${FONTFAMILY:-}" ]; then
         exit 1
     fi
 fi
-# check THEMETEX
++++ check THEMETEX +++
 if [ "${THEMETEX:-}" ]; then
     if ! [ -f "$THEMETEX" ]; then
         echo "ERROR: THEMETEX file '$THEMETEX' does not exist." 1>&2
@@ -244,6 +244,7 @@ function replacecolumns()
     local blockend=":::::::"
     local line=""
     while IFS= read -r line; do
+        line=$(echo "$line" | dos2unix) # should be a better way to strip ^M
         if [ $colcount = 0 ]; then
             if [ "$line" = "[[" ]; then
                 colcount=1
