mds checks .theme settings now. updated README.md

diff --git a/mds b/mds
--- a/mds
+++ b/mds
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -e
+set -eu
 
 if [ "${MDSDRAFT:-}" = 1 ]; then
     DRAFT=true;
@@ -116,6 +116,117 @@ if (( VERBOSE > 1 )); then
     done
 fi
 
++++ Check that the settings are valid +++
+# CHECK MAIN THEME
+validTHEMES="/AnnArbor/Antibes/Bergen/Berkeley/Berlin/Boadilla/boxes/CambridgeUS/Copenhagen/Darmstadt/default/Dresden/Frankfurt/Goettingen/Hannover/Ilmenau/JuanLesPins/Luebeck/Madrid/Malmoe/Marburg/Montpellier/PaloAlto/Pittsburgh/Rochester/Singapore/Szeged/Warsaw/"
+if ! [[  $validTHEMES =~ /${THEME}/ ]]; then
+    echo "ERROR: Invalid THEME '$THEME'. Valid choices are:${validTHEMES//\// }" 1>&2
+    exit 1
+fi
+# CHECK COLORTHEME
+validCOLORTHEMES="/albatross/beaver/beetle/crane/default/dolphin/dove/fly/lily/orchid/rose/seagull/seahorse/sidebartab/structure/whale/wolverine/"
+if ! [[  $validCOLORTHEMES =~ /${COLORTHEME}/ ]]; then
+    echo "ERROR: Invalid COLORTHEME '$COLORTHEME'. Valid choices are:${validCOLORTHEMES//\// }" 1>&2
+    exit 1
+fi
+# check INNERTHEME
+validINNERTHEMES="/default/circles/rectangles/rounded/inmargin/"
+if ! [[  $validINNERTHEMES =~ /${INNERTHEME}/ ]]; then
+    echo "ERROR: Invalid INNERTHEME '$INNERTHEME'. Valid choices are:${validINNERTHEMES//\// }" 1>&2
+    exit 1
+fi
+# check FONTTHEME
+validFONTTHEMES="/default/professionalfonts/structurebold/structureitalicserif/structuresmallcapsserif/serif/sansserif/"
+if ! [[  $validFONTTHEMES =~ /${FONTTHEME}/ ]]; then
+    echo "ERROR: Invalid FONTTHEME '$FONTTHEME'. Valid choices are:${validFONTTHEMES//\// }" 1>&2
+    exit 1
+fi
+# check HIGHLIGHT
+if [ "${HIGHLIGHT:-}" ]; then
+    validHIGHLIGHTS=$(pandoc --list-highlight-styles)
+    validHIGHLIGHTS=/${validHIGHLIGHTS//
+/\/}/
+    if ! [[  $validHIGHLIGHTS =~ /${HIGHLIGHT}/ ]]; then
+        echo "ERROR: Invalid HIGHLIGHT stye '$HIGHLIGHT'. Valid choices are:${validHIGHLIGHTS//\// }" 1>&2
+        exit 1
+    fi
+fi
+# check ASPECTRATIO
+if [ "${ASPECTRATIO:-}" ]; then
+    validASPECTRATIOS="/1610/169/149/54/43/32/"
+    if ! [[  $validASPECTRATIOS =~ /${ASPECTRATIO}/ ]]; then
+        echo "ERROR: Invalid ASPECTRATIO '$ASPECTRATIO'. Valid choices are:${validASPECTRATIOS//\// }" 1>&2
+        exit 1
+    fi
+fi
+# check LOGOONTITLE
+if [ "${LOGOONTITLE:-}" ]; then
+    validLOGOONTITLES="/true/false/"
+    if ! [[  $validLOGOONTITLES =~ /${LOGOONTITLE}/ ]]; then
+        echo "ERROR: Invalid value '$LOGOONTITLE' for LOGOONTITLE. Valid choices are:${validLOGOONTITLES//\// }" 1>&2
+        exit 1
+    fi
+fi
+# check LOGOHEIGHT
+if [ "${LOGOHEIGHT:-}" ]; then
+    if ! [[ $LOGOHEIGHT =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
+        echo "ERROR: Invalid number '$LOGOHEIGHT' for LOGOHEIGHT." 1>&2
+        exit 1
+    fi
+fi
+# check LOGOWIDTH
+if [ "${LOGOWIDTH:-}" ]; then
+    if ! [[ $LOGOWIDTH =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
+        echo "ERROR: Invalid number '$LOGOWIDTH' for LOGOWIDTH." 1>&2
+        exit 1
+    fi
+fi
+# check LOGOUP
+if [ "${LOGOUP:-}" ]; then
+    if ! [[ $LOGOUP =~ ^[0-9]*(\.[0-9]+)?$ ]]; then
+        echo "ERROR: Invalid number '$LOGOUP' for LOGOUP." 1>&2
+        exit 1
+    fi
+fi
+# check LOGO
+if [ "${LOGO:-}" ]; then
+  compatibleTHEMES="/AnnArbor/Antibes/Bergen/Berkeley/Berlin/Boadilla/boxes/CambridgeUS/Copenhagen/Darmstadt/default/Dresden/Frankfurt/Ilmenau/JuanLesPins/Luebeck/Madrid/Malmoe/Montpellier/PaloAlto/Pittsburgh/Rochester/Singapore/Szeged/Warsaw/"
+    if ! [[  $compatibleTHEMES =~ /${THEME}/ ]]; then
+        echo "WARNING: THEME '$THEME' does not support a LOGO. LOGO compatible choices are:${compatibleTHEMES//\// }" 1>&2
+        sleep 5
+    fi
+    # check existance
+    if ! [ -f "$LOGO" ]; then
+        echo "ERROR: Logo file '$LOGO' does not exist." 1>&2
+        exit 2
+    fi
+fi
+# check FONTSIZE
+if [ "${FONTSIZE:-}" ]; then
+    validFONTSIZES="/8pt/9pt/10pt/11pt/12pt/14pt/17pt/20pt/"
+    if ! [[  $validFONTSIZES =~ /${FONTSIZE}/ ]]; then
+        echo "ERROR: Invalid FONTSIZE '$FONTSIZE'. Valid choices are:${validFONTSIZES//\//, }" 1>&2
+        exit 1
+    fi
+fi
+# check FONTFAMILY
+if [ "${FONTFAMILY:-}" ]; then
+    validFONTFAMILIES=$(fc-list : family | tr ',' '\n' | sort -u)
+    validFONTFAMILIES=/${validFONTFAMILIES//
+/\/}/
+    if ! [[  $validFONTFAMILIES =~ /${FONTFAMILY}/ ]]; then
+        echo "ERROR: Invalid FONTFAMILY '$FONTFAMILY'. Valid choices are:${validFONTFAMILIES//\//, }" 1>&2
+        exit 1
+    fi
+fi
+# check THEMETEX
+if [ "${THEMETEX:-}" ]; then
+    if ! [ -f "$THEMETEX" ]; then
+        echo "ERROR: THEMETEX file '$THEMETEX' does not exist." 1>&2
+        exit 2
+    fi
+fi
+
 if [ $ENGINE = xelatex ]; then
     ENGINEDRAFTMODEOPTION=--no-pdf
 else
@@ -128,6 +239,7 @@ function replacecolumns()
 {
     local tempfile=$(mktemp)
     local colcount=0
+    local firstcolwidth=0
     local blockstart=":::::::{.block}"
     local blockend=":::::::"
     local line=""
@@ -135,6 +247,7 @@ function replacecolumns()
         if [ $colcount = 0 ]; then
             if [ "$line" = "[[" ]; then
                 colcount=1
+                firstcolwidth=$colcount
                 \rm -f "$tempfile"
                 touch "$tempfile"
             else
